services:
  langgraph-qna:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
